name: calc_example_frontend
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  go_router: ^16.0.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  go_router_builder: ^3.0.1
  build_runner: ^2.4.15
  build_verify: ^3.1.1
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - .env